version: '3.9'

networks:
  ticket_sales-network:
    attachable: true

volumes:
  postgresdb_data:

services:
  ticket_sales-postgresdb:
    image: 'postgres:13.11-bullseye'
    container_name: ticket_sales_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    networks:
      - ticket_sales-network
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure