lombok:
  addLombokGeneratedAnnotation: true

// Server port
server:
  port: 8080

// Spring properties
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8080/database
    username: Tikhon
    password: "qwerty"